# Generated by Django 4.0.4 on 2022-05-12 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertransaction',
            options={'ordering': ['-created']},
        ),
    ]
